[[constraint]]
  branch = "master"
  name = "github.com/yfronto/go-statuspage-api"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/buildkite/statusbot"
  go-version = "1.10.2"
  install = [ "./..." ]
