steps:
  - label: ":golang:"
    plugins:
      golang-cross-compile#v1.1.0:
        build: .
        import: github.com/buildkite/statusbot
        targets:
          - version: 1.10.3
            goos: linux
            goarch: amd64
          - version: 1.10.3
            goos: windows
            goarch: amd64
          - version: 1.10.3
            goos: darwin
            goarch: amd64
          - version: 1.10.3
            goos: freebsd
            goarch: amd64

