steps:
  - name: ":linux: amd64"
    command: .buildkite/steps/build-binary.sh linux amd64
    plugins:
      - artifacts#5ad26ec:
          upload: "dist/*"

  - wait
  - name: ":ecs: Deploy"
    command: .buildkite/steps/deploy-ecs.sh
    agents:
      queue: deploy

