steps:
  - label: ":golang:"
    plugins:
      golang-cross-compile#v1.0.0:
        build: .
        import: github.com/buildkite/statusbot
        targets:
          - version: 1.10.3
            os: linux
            arch: amd64
          - version: 1.10.3
            os: windows
            arch: amd64
          - version: 1.10.3
            os: darwin
            arch: amd64
          - version: 1.10.3
            os: freebsd
            arch: amd64

